---
kind: pipeline
name: python3-java
type: docker

steps:
- name: test
  image: felixocker/python3_java:latest
  commands:
  - pip install -r requirements.txt
  - pip install .
  - python -m unittest discover tests

# To save energy and resources ci should only run for a few branches
# Related section of the docs: https://docs.drone.io/pipeline/triggers/
# Strategy: push regularly to branch `develop` and occasionally to `develop_ci` (only when ci should run)
trigger:
  branch:
    - main
    - develop_ci
